# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('SYSTEM', '系统'), ('COMPETITION', '竞赛'), ('TEAM', '组队'), ('ACTIVITY', '活动'), ('ORGANIZATION', '组织'), ('CONSULTATION', '咨询')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('action_path', models.CharField(blank=True, max_length=500, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notif_recipient_created_idx'), models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_read_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('recipient', 'dedupe_key'), name='notification_dedupe_unique')],
            },
        ),
    ]
