# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('TEAM_RECRUITING', '队伍招募'), ('PERSON_LOOKING', '个人找队')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(max_length=500)),
                ('members_summary', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('base_member_count', models.SmallIntegerField()),
                ('target_member_count', models.SmallIntegerField()),
                ('goal', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('weekly_commitment', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_method', models.CharField(choices=[('WECHAT', '微信'), ('QQ', 'QQ'), ('PHONE', '电话'), ('EMAIL', '邮箱'), ('OTHER', '其他')], max_length=20)),
                ('contact_value', models.CharField(max_length=200)),
                ('notes_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('status', models.CharField(choices=[('RECRUITING', '招募中'), ('FULL', '已满员'), ('CLOSED', '已关闭')], default='RECRUITING', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_posts', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_posts', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('headcount', models.SmallIntegerField()),
                ('requirements', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('team_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='teams.teampost')),
            ],
        ),
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_intro', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('motivation', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('weekly_commitment', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_method', models.CharField(choices=[('WECHAT', '微信'), ('QQ', 'QQ'), ('PHONE', '电话'), ('EMAIL', '邮箱'), ('OTHER', '其他')], max_length=20)),
                ('contact_value', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝'), ('WITHDRAWN', '已撤回')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_applications', to=settings.AUTH_USER_MODEL)),
                ('team_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='teams.teampost')),
                ('desired_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='teams.teamrole')),
            ],
        ),
        migrations.AddIndex(
            model_name='teampost',
            index=models.Index(fields=['competition', 'status', 'created_at'], name='team_post_comp_state_idx'),
        ),
        migrations.AddIndex(
            model_name='teampost',
            index=models.Index(fields=['author', 'created_at'], name='team_post_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='teampost',
            index=models.Index(fields=['post_type', 'status', 'created_at'], name='team_post_type_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='teampost',
            constraint=models.CheckConstraint(condition=models.Q(('base_member_count__gte', 1)), name='team_post_base_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='teampost',
            constraint=models.CheckConstraint(condition=models.Q(('target_member_count__gte', models.F('base_member_count'))), name='team_post_target_count_valid'),
        ),
        migrations.AddConstraint(
            model_name='teamrole',
            constraint=models.UniqueConstraint(fields=('team_post', 'name'), name='team_role_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='teamrole',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gt', 0)), name='team_role_headcount_positive'),
        ),
        migrations.AddConstraint(
            model_name='teamrole',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='team_role_sort_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='teamapplication',
            index=models.Index(fields=['team_post', 'status', 'created_at'], name='team_app_post_state_idx'),
        ),
        migrations.AddIndex(
            model_name='teamapplication',
            index=models.Index(fields=['applicant', 'created_at'], name='team_app_applicant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('team_post', 'applicant'), name='team_application_active_unique'),
        ),
    ]
