# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('competitions', '0001_initial'),
        ('media', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('COMPETITION', '竞赛'), ('RESEARCH', '科研'), ('FURTHER_STUDY', '升学'), ('CERTIFICATE', '证书'), ('PROCESS', '流程'), ('EXPERIENCE', '经验'), ('OTHER', '其他')], max_length=30)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('body_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideCompetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_links', to='competitions.competition')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_links', to='content.guidearticle')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=160, null=True)),
                ('category_label', models.CharField(blank=True, max_length=30, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=160, null=True)),
                ('link_type', models.CharField(choices=[('NONE', '无链接'), ('INTERNAL', '站内链接'), ('EXTERNAL', '站外链接')], default='NONE', max_length=20)),
                ('internal_path', models.CharField(blank=True, max_length=500, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homepage_banners', to='media.mediaasset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_banners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('body_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('publisher_scope', models.CharField(choices=[('ACADEMY', '学院'), ('UNIVERSITY', '学校'), ('PLATFORM', '平台')], max_length=20)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='activities.activity')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='competitions.competition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organizations.organization')),
                ('recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organizations.recruitment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['publication_state', 'published_at'], name='announcement_state_pub_idx'), models.Index(fields=['is_pinned', 'published_at'], name='announcement_pinned_pub_idx'), models.Index(fields=['competition', 'publication_state'], name='announcement_comp_state_idx'), models.Index(fields=['activity', 'publication_state'], name='announcement_activity_idx'), models.Index(fields=['organization', 'publication_state'], name='announcement_org_state_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('COMPETITION', '竞赛'), ('RESEARCH', '科研'), ('FURTHER_STUDY', '升学'), ('CERTIFICATE', '证书'), ('PROCESS', '流程'), ('EXPERIENCE', '经验'), ('OTHER', '其他')], max_length=30)),
                ('question', models.CharField(max_length=300)),
                ('answer_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_faq_items', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_faq_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['publication_state', 'sort_order'], name='faq_state_sort_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='faq_sort_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='guidearticle',
            index=models.Index(fields=['category', 'publication_state', 'published_at'], name='guide_category_state_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='guidearticle',
            index=models.Index(fields=['is_featured', 'featured_order'], name='guide_featured_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidearticle',
            constraint=models.CheckConstraint(condition=models.Q(('featured_order__gte', 0)), name='guide_featured_order_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='guidecompetition',
            constraint=models.UniqueConstraint(fields=('guide', 'competition'), name='guide_competition_unique'),
        ),
        migrations.AddConstraint(
            model_name='guidecompetition',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='guide_competition_sort_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='homepagebanner',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('start_at__lte', models.F('end_at')), _connector='OR'), name='homepage_banner_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='homepagebanner',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='homepage_banner_sort_nonnegative'),
        ),
    ]
