# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('COMPETITION', '竞赛'), ('TEAM', '组队'), ('ORGANIZATION', '组织'), ('ACTIVITY', '活动'), ('FURTHER_STUDY', '升学'), ('CERTIFICATE', '证书'), ('OTHER', '其他')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('visibility', models.CharField(choices=[('PUBLIC', '公开'), ('PRIVATE', '私密')], default='PRIVATE', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', '待回复'), ('ANSWERED', '已回复'), ('CLOSED', '已关闭')], default='OPEN', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_replies', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='consultations.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['author', 'created_at'], name='consult_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status', 'visibility', 'created_at'], name='consult_state_visibility_idx'),
        ),
    ]
