# Generated by Django 5.2.17 on 2026-08-26 04:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="上次登录")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, help_text="指明该用户缺省拥有所有权限。", verbose_name="超级用户状态"),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "已存在一位使用该名字的用户。"},
                        help_text="必填；长度为150个字符或以下；只能包含字母、数字、特殊字符“@”、“.”、“-”和“_”。",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="用户名",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="名字")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="姓氏")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="电子邮件地址")),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="指明用户是否可以登录到这个管理站点。", verbose_name="工作人员状态"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="指明用户是否被认为是活跃的。以反选代替删除帐号。", verbose_name="有效"),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="加入日期")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_no", models.CharField(blank=True, max_length=32, null=True)),
                ("real_name", models.CharField(max_length=80)),
                (
                    "platform_role",
                    models.CharField(
                        choices=[("STUDENT", "学生"), ("OPERATOR", "运营人员")],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="该用户归属的组。一个用户将得到其归属的组的所有权限。",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="组",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="这个用户的特定权限。",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="用户权限",
                    ),
                ),
            ],
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nickname", models.CharField(blank=True, max_length=40, null=True)),
                ("major", models.CharField(blank=True, max_length=80, null=True)),
                ("grade", models.SmallIntegerField(blank=True, null=True)),
                ("class_name", models.CharField(blank=True, max_length=80, null=True)),
                ("bio", models.CharField(blank=True, max_length=500, null=True)),
                ("skills_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["platform_role", "is_active"], name="accounts_user_role_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student_no__isnull", False)),
                fields=("student_no",),
                name="accounts_user_student_no_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("grade__isnull", True),
                    models.Q(("grade__gte", 1), ("grade__lte", 4)),
                    _connector="OR",
                ),
                name="accounts_profile_grade_range",
            ),
        ),
    ]
