# Generated by Django 5.2.17 on 2026-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_identity_check'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_identity_no_check',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee_no__isnull', True), ('identity_type', 'STUDENT'), ('student_no__isnull', False)), models.Q(('employee_no__isnull', False), ('identity_type', 'TEACHER'), ('student_no__isnull', True)), ('is_superuser', True), models.Q(('employee_no__isnull', True), ('is_active', False), ('student_no__isnull', True)), _connector='OR'), name='accounts_user_identity_no_check'),
        ),
    ]
