# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('edition', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('AI', '人工智能'), ('PROGRAMMING', '编程'), ('INNOVATION', '创新'), ('MATHEMATICAL_MODELING', '数学建模'), ('ELECTRONICS', '电子'), ('ROBOTICS', '机器人'), ('OTHER', '其他')], max_length=30)),
                ('level', models.CharField(choices=[('SCHOOL', '校级'), ('PROVINCIAL', '省级'), ('NATIONAL', '国家级'), ('INTERNATIONAL', '国际'), ('OTHER', '其他')], max_length=30)),
                ('participation_mode', models.CharField(choices=[('INDIVIDUAL', '个人'), ('TEAM', '团队')], max_length=20)),
                ('suitable_grade_min', models.SmallIntegerField(blank=True, null=True)),
                ('suitable_grade_max', models.SmallIntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('description_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('suitable_for_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('preparation_advice_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('registration_start_at', models.DateTimeField(blank=True, null=True)),
                ('registration_end_at', models.DateTimeField(blank=True, null=True)),
                ('event_start_at', models.DateTimeField(blank=True, null=True)),
                ('event_end_at', models.DateTimeField(blank=True, null=True)),
                ('college_organized', models.BooleanField(default=False)),
                ('college_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_contact_text', models.CharField(blank=True, max_length=200, null=True)),
                ('official_url', models.URLField(blank=True, max_length=500, null=True)),
                ('registration_url', models.URLField(blank=True, max_length=500, null=True)),
                ('official_notice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('CANCELLED', '已取消'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.IntegerField(default=0)),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_covers', to='media.mediaasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follows', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('event_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to='competitions.competition')),
            ],
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['publication_state', 'registration_end_at'], name='competition_state_reg_end_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['category', 'publication_state'], name='competition_category_state_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['level', 'publication_state'], name='competition_level_state_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['participation_mode', 'publication_state'], name='competition_mode_state_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['is_featured', 'featured_order'], name='competition_featured_order_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['event_start_at'], name='competition_event_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('name', 'edition'), name='competition_name_edition_unique'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_start_at__isnull', True), ('registration_end_at__isnull', True), ('registration_start_at__lte', models.F('registration_end_at')), _connector='OR'), name='competition_registration_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('event_start_at__isnull', True), ('event_end_at__isnull', True), ('event_start_at__lte', models.F('event_end_at')), _connector='OR'), name='competition_event_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('suitable_grade_min__isnull', True), models.Q(('suitable_grade_min__gte', 1), ('suitable_grade_min__lte', 4)), _connector='OR'), name='competition_grade_min_range'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('suitable_grade_max__isnull', True), models.Q(('suitable_grade_max__gte', 1), ('suitable_grade_max__lte', 4)), _connector='OR'), name='competition_grade_max_range'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('suitable_grade_min__isnull', True), ('suitable_grade_max__isnull', True), ('suitable_grade_min__lte', models.F('suitable_grade_max')), _connector='OR'), name='competition_grade_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('featured_order__gte', 0)), name='competition_featured_order_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'competition'), name='competition_follow_unique'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['competition', 'event_at'], name='timeline_competition_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('event_at__lte', models.F('end_at')), _connector='OR'), name='timeline_event_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='timeline_event_sort_nonnegative'),
        ),
    ]
