# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('IMAGE', '图片'), ('DOCUMENT', '文档')], max_length=20)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '可用'), ('PENDING_DELETE', '待删除'), ('DELETED', '已删除')], default='ACTIVE', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sha256'], name='media_asset_sha256_idx'), models.Index(fields=['status', 'created_at'], name='media_asset_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='media_asset_size_positive'), models.CheckConstraint(condition=models.Q(('kind', 'IMAGE'), models.Q(('width__isnull', True), ('height__isnull', True)), _connector='OR'), name='media_asset_dimensions_image_only')],
            },
        ),
    ]
