# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('activity_type', models.CharField(choices=[('COMPETITION_BRIEFING', '竞赛说明'), ('TECH_SHARING', '技术分享'), ('RESEARCH_LECTURE', '学术讲座'), ('FURTHER_STUDY', '升学'), ('ENTERPRISE', '企业'), ('TRAINING', '培训'), ('OTHER', '其他')], max_length=30)),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('description_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('organizer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('speaker', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_start_at', models.DateTimeField(blank=True, null=True)),
                ('registration_end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('notes_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('CANCELLED', '已取消'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.IntegerField(default=0)),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_covers', to='media.mediaasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('organizer_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REGISTERED', '已报名'), ('CANCELLED', '已取消')], default='REGISTERED', max_length=20)),
                ('name_snapshot', models.CharField(max_length=80)),
                ('student_no_snapshot', models.CharField(max_length=32)),
                ('class_name_snapshot', models.CharField(blank=True, max_length=80, null=True)),
                ('major_snapshot', models.CharField(blank=True, max_length=80, null=True)),
                ('grade_snapshot', models.SmallIntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['publication_state', 'start_at'], name='activity_state_start_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'publication_state'], name='activity_type_state_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['registration_end_at'], name='activity_registration_end_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_featured', 'featured_order'], name='activity_featured_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('start_at__lte', models.F('end_at')), _connector='OR'), name='activity_event_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('registration_start_at__isnull', True), ('registration_end_at__isnull', True), ('registration_start_at__lte', models.F('registration_end_at')), _connector='OR'), name='activity_registration_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='activity_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('featured_order__gte', 0)), name='activity_featured_order_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('registration_required', True), models.Q(('registration_start_at__isnull', True), ('registration_end_at__isnull', True), ('capacity__isnull', True)), _connector='OR'), name='activity_registration_fields_required_only'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['activity', 'status'], name='activity_reg_state_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'status'], name='activity_reg_user_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='activity_registration_unique'),
        ),
    ]
