# Generated by Django 5.2.17 on 2026-08-26 05:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('organization_type', models.CharField(choices=[('COLLEGE_DEPARTMENT', '学院部门'), ('STUDENT_CLUB', '学生社团'), ('LABORATORY', '实验室'), ('INNOVATION_TEAM', '科创团队'), ('OTHER', '其他')], max_length=30)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('description_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('advisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('public_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banner_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_banners', to='media.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_logos', to='media.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', '成员'), ('LEADER', '负责人')], default='MEMBER', max_length=20)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('intro_md', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('apply_start_at', models.DateTimeField(blank=True, null=True)),
                ('apply_end_at', models.DateTimeField()),
                ('target_grade_min', models.SmallIntegerField(blank=True, null=True)),
                ('target_grade_max', models.SmallIntegerField(blank=True, null=True)),
                ('notes_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('publication_state', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('CANCELLED', '已取消'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recruitments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitments', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_recruitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('headcount', models.SmallIntegerField()),
                ('description_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('requirements_md', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('sort_order', models.IntegerField(default=0)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organizations.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('self_intro', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('motivation', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝'), ('WITHDRAWN', '已撤回')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_applications', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_recruitment_applications', to=settings.AUTH_USER_MODEL)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organizations.recruitment')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organizations.recruitmentposition')),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type', 'is_active'], name='organization_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='membership_org_role_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='organization_membership_unique'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['organization', 'publication_state'], name='recruitment_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['publication_state', 'apply_end_at'], name='recruitment_state_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('apply_start_at__isnull', True), ('apply_start_at__lte', models.F('apply_end_at')), _connector='OR'), name='recruitment_apply_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('target_grade_min__isnull', True), models.Q(('target_grade_min__gte', 1), ('target_grade_min__lte', 4)), _connector='OR'), name='recruitment_grade_min_range'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('target_grade_max__isnull', True), models.Q(('target_grade_max__gte', 1), ('target_grade_max__lte', 4)), _connector='OR'), name='recruitment_grade_max_range'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('target_grade_min__isnull', True), ('target_grade_max__isnull', True), ('target_grade_min__lte', models.F('target_grade_max')), _connector='OR'), name='recruitment_grade_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentposition',
            constraint=models.UniqueConstraint(fields=('recruitment', 'name'), name='recruitment_position_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentposition',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gt', 0)), name='recruitment_position_headcount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentposition',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='recruitment_position_sort_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['recruitment', 'status', 'created_at'], name='recruit_app_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['position', 'status'], name='recruit_app_position_state_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['applicant', 'created_at'], name='recruit_applicant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('recruitment', 'applicant'), name='recruitment_application_active_unique'),
        ),
    ]
